//------------------------------------------------------------------------------
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileType: SOURCE
// SPDX-FileCopyrightText: (c) 2026, ThinkElastic <Think@Elastic.com>
//------------------------------------------------------------------------------

// Generated by tools/generate_lsu_shim.py from the production inline shim.
// Do not edit the body: GPU integration tests must exercise the same RTL.
// Run make gpu-chain to refresh after a cpu_system.v change.

`default_nettype none

module lsu_axi_shim (
    input  wire        clk,
    input  wire        reset,

    // ============================================================
    // LSU cmd/rsp bus (upstream — from VexiiRiscv or testbench)
    // ============================================================
    input  wire        lsu_cmd_valid,
    output wire        lsu_cmd_ready,
    input  wire        lsu_cmd_write,
    input  wire [31:0] lsu_cmd_addr,
    input  wire [31:0] lsu_cmd_data,
    input  wire [3:0]  lsu_cmd_mask,
    output wire        lsu_rsp_valid,
    output wire        lsu_rsp_error,
    output wire [31:0] lsu_rsp_data,

    // ============================================================
    // AXI4 master (downstream — to slices / cpu_target_port)
    // ============================================================
    output wire        per_arvalid_cpu,
    input  wire        per_arready_cpu,
    output wire [31:0] per_araddr_cpu,
    output wire [7:0]  per_arlen_cpu,

    input  wire        per_rvalid_cpu,
    output wire        per_rready_cpu,
    input  wire [31:0] per_rdata_cpu,
    input  wire [1:0]  per_rresp_cpu,
    input  wire        per_rlast_cpu,

    output wire        per_awvalid_cpu,
    input  wire        per_awready_cpu,
    output wire [31:0] per_awaddr_cpu,
    output wire [7:0]  per_awlen_cpu,
    output wire [1:0]  per_awburst_cpu,

    output wire        per_wvalid_cpu,
    input  wire        per_wready_cpu,
    output wire [31:0] per_wdata_cpu,
    output wire [3:0]  per_wstrb_cpu,
    output wire        per_wlast_cpu,

    input  wire        per_bvalid_cpu,
    output wire        per_bready_cpu,
    input  wire [1:0]  per_bresp_cpu
);

// Read tracker — 1-deep.
reg        lsu_inflight_read;
reg        lsu_ar_sent;
reg [31:0] lsu_rd_addr;

// Write FIFO — 4-deep posted-write queue.
localparam WR_FIFO_DEPTH = 4;
localparam WR_PTR_W      = 2;  // log2(WR_FIFO_DEPTH)
localparam WR_CNT_W      = 3;  // log2(WR_FIFO_DEPTH+1)

reg [31:0] wr_addr_mem [0:WR_FIFO_DEPTH-1];
reg [31:0] wr_data_mem [0:WR_FIFO_DEPTH-1];
reg [3:0]  wr_mask_mem [0:WR_FIFO_DEPTH-1];
// Equality with the preceding queue entry is fixed when an entry is pushed.
// Cache that comparison once instead of multiplexing and comparing three
// pairs of 36-bit address/mask values on the AW path. The oldest entry's
// flag is never used; count gating excludes stale entries after a pop.
reg [WR_FIFO_DEPTH-1:0] wr_matches_prev;
reg [WR_PTR_W-1:0] wr_head, wr_tail;
reg [WR_CNT_W-1:0] wr_count;
reg                lsu_aw_sent, lsu_w_sent;  // per-head AW/W issue tracking

wire wr_fifo_full  = (wr_count == WR_FIFO_DEPTH);
wire wr_fifo_empty = (wr_count == 0);

// M2 coalescer state.  When the FIFO holds N consecutive same-address
// same-mask entries at the head, fire one AW with awlen=N-1
// and awburst=FIXED, pump N W-beats from FIFO[head..head+N-1], then
// pop all N entries on B. burst_awlen_calc scans the current queue;
// presented_awlen freezes an offered burst if AW stalls, and burst_awlen
// records its accepted length for WLAST. This still helps
// repeated writes to one MMIO register, such as LUT uploads.
reg [WR_PTR_W-1:0] burst_awlen;
reg [WR_PTR_W-1:0] burst_w_idx;
reg                awlen_held;
reg [WR_PTR_W-1:0] held_awlen;

// Accept logic.  A write enters the FIFO whenever it has room AND
// no read is in flight (read drained first; writes don't pass reads
// because the CPU's LSU stalls on read rsp anyway).  A read fires
// when no writes are pending and no other read is outstanding.
wire lsu_cmd_can_accept_wr = !lsu_inflight_read && !wr_fifo_full;
wire lsu_cmd_can_accept_rd = !lsu_inflight_read && wr_fifo_empty;
wire lsu_cmd_can_accept    =  lsu_cmd_write ? lsu_cmd_can_accept_wr
                                            : lsu_cmd_can_accept_rd;
wire lsu_cmd_fire = lsu_cmd_valid && lsu_cmd_can_accept;
wire wr_push     = lsu_cmd_fire & lsu_cmd_write;
wire wr_pop      = per_bvalid_cpu & per_bready_cpu;

// Posted-write rsp: pulse one cycle after the FIFO push so the CPU
// retires the store and pipelines the next.  Read rsp is when R-last lands.
reg wr_rsp_q;
always @(posedge clk or posedge reset) begin
    if (reset) wr_rsp_q <= 1'b0;
    else       wr_rsp_q <= wr_push;
end

assign lsu_rsp_valid = (per_rvalid_cpu & per_rready_cpu & per_rlast_cpu)
                     | wr_rsp_q;
assign lsu_rsp_data  = per_rdata_cpu;
// Surface read errors only; write errors are dropped (writes posted).
assign lsu_rsp_error = (per_rvalid_cpu & per_rready_cpu & per_rlast_cpu)
                       ? (per_rresp_cpu != 2'b00)
                       : 1'b0;
assign lsu_cmd_ready = lsu_cmd_can_accept;

// Read FSM — 1-deep, identical behavior to the previous shim.
always @(posedge clk or posedge reset) begin
    if (reset) begin
        lsu_inflight_read <= 1'b0;
        lsu_ar_sent       <= 1'b0;
        lsu_rd_addr       <= 32'b0;
    end else begin
        if (lsu_cmd_fire && !lsu_cmd_write) begin
            lsu_rd_addr <= lsu_cmd_addr;
        end
        if (per_arvalid_cpu && per_arready_cpu) lsu_ar_sent <= 1'b1;
        if (per_rvalid_cpu  && per_rready_cpu && per_rlast_cpu) begin
            lsu_inflight_read <= 1'b0;
            lsu_ar_sent       <= 1'b0;
        end else if (lsu_cmd_fire && !lsu_cmd_write) begin
            lsu_inflight_read <= 1'b1;
        end
    end
end

// M2 match scan: how many consecutive head entries share addr+mask?
// burst_awlen_calc is N-1 (0=single beat, 3=4-beat burst).  Combinational
// — at the AW handshake posedge, both the slice and our burst_awlen
// register sample the same value, so they stay consistent through the
// W phase.
wire [WR_PTR_W-1:0] head1 = wr_head + {{(WR_PTR_W-1){1'b0}}, 1'b1};
wire [WR_PTR_W-1:0] head2 = wr_head + 2'd2;
wire [WR_PTR_W-1:0] head3 = wr_head + 2'd3;
// Same-address FIXED-burst coalescing is only legal for the LOCAL (periph)
// target, which honors awburst==FIXED (req_addr held across beats).  The
// SDRAM and CRAM0 target ports leave m_awburst unconnected and treat any
// multi-beat write as INCR, so a coalesced FIXED burst routed there would
// scatter the 2nd..Nth beats to addr+4, addr+8, ... and corrupt memory.
// Gate coalescing on the head address decoding to LOCAL; otherwise force
// burst_awlen_calc=0 (single INCR beat).  (Decoded inline here because
// decode_target is defined later in the file.)
wire [31:0] coalesce_addr = wr_addr_mem[wr_head];
wire coalesce_is_sdram = (coalesce_addr[31:26] == 6'b000100)
                      || (coalesce_addr[31:26] == 6'b010100);
wire coalesce_is_cram0 = (coalesce_addr[31:24] == 8'h30)
                      || (coalesce_addr[31:24] == 8'h38);
wire coalesce_ok = !coalesce_is_sdram && !coalesce_is_cram0; // LOCAL only
wire match01 = coalesce_ok
            && (wr_count >= 3'd2)
            && wr_matches_prev[head1];
wire match02 = match01 && (wr_count >= 3'd3)
            && wr_matches_prev[head2];
wire match03 = match02 && (wr_count >= 3'd4)
            && wr_matches_prev[head3];

wire [WR_PTR_W-1:0] burst_awlen_calc = match03 ? 2'd3
                                     : match02 ? 2'd2
                                     : match01 ? 2'd1
                                     : 2'd0;
// Once AW is presented, additional pushes cannot extend its advertised
// burst under backpressure. Capture the first stalled presentation; a
// ready target still accepts the current run without an extra cycle.
wire [WR_PTR_W-1:0] presented_awlen = awlen_held ? held_awlen : burst_awlen_calc;

// W-beat data routing: head + w_idx for both single-beat and burst.
wire [WR_PTR_W-1:0] w_idx     = wr_head + burst_w_idx;
wire [31:0]         w_addr    = wr_addr_mem[wr_head];   // FIXED: same every beat
wire [31:0]         w_data    = wr_data_mem[w_idx];
wire [3:0]          w_mask    = wr_mask_mem[w_idx];
// W may be accepted before, with, or after AW. Before AW acceptance,
// WLAST must describe the presented burst, including while W is stalled;
// afterwards it uses the accepted length. The previous transaction's
// burst_awlen is never valid for a newly presented W beat.
wire [WR_PTR_W-1:0] eff_burst_awlen =
    lsu_aw_sent ? burst_awlen : presented_awlen;
wire                w_is_last = (burst_w_idx == eff_burst_awlen);

// Write FIFO push/pop and burst tracking.
integer wi;
wire [WR_PTR_W-1:0] wr_previous = wr_tail - 2'd1;
always @(posedge clk or posedge reset) begin
    if (reset) begin
        wr_head     <= {WR_PTR_W{1'b0}};
        wr_tail     <= {WR_PTR_W{1'b0}};
        wr_count    <= {WR_CNT_W{1'b0}};
        wr_matches_prev <= 0;
        lsu_aw_sent <= 1'b0;
        lsu_w_sent  <= 1'b0;
        burst_awlen <= {WR_PTR_W{1'b0}};
        burst_w_idx <= {WR_PTR_W{1'b0}};
        awlen_held <= 1'b0;
        held_awlen <= 0;
        for (wi = 0; wi < WR_FIFO_DEPTH; wi = wi + 1) begin
            wr_addr_mem[wi] <= 32'b0;
            wr_data_mem[wi] <= 32'b0;
            wr_mask_mem[wi] <= 4'b0;
        end
    end else begin
        if (wr_push) begin
            wr_matches_prev[wr_tail] <=
                (lsu_cmd_addr == wr_addr_mem[wr_previous]) &&
                (lsu_cmd_mask == wr_mask_mem[wr_previous]);
            wr_addr_mem[wr_tail] <= lsu_cmd_addr;
            wr_data_mem[wr_tail] <= lsu_cmd_data;
            wr_mask_mem[wr_tail] <= lsu_cmd_mask;
            wr_tail              <= wr_tail + {{(WR_PTR_W-1){1'b0}}, 1'b1};
        end

        // B retires the entire burst — pop burst_awlen+1 entries, reset
        // per-burst state so the next AW handshake re-latches.
        if (wr_pop) begin
            wr_head     <= wr_head + (burst_awlen + {{(WR_PTR_W-1){1'b0}}, 1'b1});
            lsu_aw_sent <= 1'b0;
            lsu_w_sent  <= 1'b0;
            burst_w_idx <= {WR_PTR_W{1'b0}};
        end

        // AW handshake: latch awlen for the W phase + mark sent.
        if (per_awvalid_cpu && per_awready_cpu) begin
            lsu_aw_sent <= 1'b1;
            burst_awlen <= presented_awlen;
            awlen_held <= 1'b0;
        end else if (per_awvalid_cpu && !awlen_held) begin
            held_awlen <= burst_awlen_calc;
            awlen_held <= 1'b1;
        end

        // W beat: advance w_idx, set w_sent on wlast.
        if (per_wvalid_cpu && per_wready_cpu) begin
            if (w_is_last) lsu_w_sent <= 1'b1;
            else           burst_w_idx <= burst_w_idx + {{(WR_PTR_W-1){1'b0}}, 1'b1};
        end

        // FIFO count delta accounts for posted push and burst-sized pop.
        case ({wr_push, wr_pop})
            2'b10: wr_count <= wr_count + 3'd1;
            2'b01: wr_count <= wr_count - {1'b0, burst_awlen} - 3'd1;
            2'b11: wr_count <= wr_count - {1'b0, burst_awlen};
            default: ;
        endcase
    end
end

// AR channel — drive while we have a read in flight but AR not yet accepted.
assign per_arvalid_cpu = lsu_inflight_read & ~lsu_ar_sent;
assign per_araddr_cpu  = lsu_rd_addr;
assign per_arlen_cpu   = 8'd0;
assign per_rready_cpu  = 1'b1;

// AW channel. Length and burst type describe the presented run and stay
// stable under backpressure. The target and our burst_awlen register
// sample the same value on the AW handshake edge.
// awburst=FIXED when coalescing keeps req_addr pinned across beats;
// awburst=INCR for single beats so
// non-burst-aware slaves keep their existing behavior.
assign per_awvalid_cpu = !wr_fifo_empty & ~lsu_aw_sent;
assign per_awaddr_cpu  = w_addr;
assign per_awlen_cpu   = {{(8-WR_PTR_W){1'b0}}, presented_awlen};
assign per_awburst_cpu = (presented_awlen != {WR_PTR_W{1'b0}}) ? 2'b00 : 2'b01;

// W channel — beat data from FIFO[head + w_idx]; wlast on the final beat.
assign per_wvalid_cpu  = !wr_fifo_empty & ~lsu_w_sent;
assign per_wdata_cpu   = w_data;
assign per_wstrb_cpu   = w_mask;
assign per_wlast_cpu   = w_is_last;
assign per_bready_cpu  = 1'b1;

endmodule

`default_nettype wire
